api:
  dashboard: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
  https:
    address: ":443"

global:
  checknewversion: true
  sendanonymoususage: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

metrics:
  prometheus: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: p_konsti@outlook.de
      storage: acme.json
      tlsChallenge: {}
      httpChallenge:
        entryPoint: web
